baseurl = "https://invisibook-lab.github.io"
title = "Invisibook"
theme = "cleanwhite"
languageCode = "zh-cn"
preserveTaxonomyNames = true
hasCJKLanguage = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    shortname = ""
  [services.googleAnalytics]
    id = ""

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "img/home-bg-jeep.jpg"
  SEOTitle = "Invisibook"
  description = "Invisibook Lab - 探索技术，分享知识"
  keyword = "Invisibook, 技术博客, 编程, 开发"
  slogan = "探索技术，分享知识"
  upstreamAttribution = true

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  sidebar_about_description = "探索技术，分享知识"
  #sidebar_avatar = "img/avatar.jpg"

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # Disqus proxy
  disqus_proxy = ""
  disqus_site = ""

  # Twikoo comments
  twikoo_env_id = ""

  # Artalk comments
  artalk_enable = false
  artalk_server = ""
  artalk_site = ""

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  reward = false 

  friends = false
  bookmarks = false
  about_me = false

  # Last posts
  last_posts = true

  [params.social]
  rss            = true 
  email          = ""
  github         = "https://github.com/invisibook-lab"
  
  [[params.additional_menus]]
  title =  "ARCHIVE"
  href =  "/archive/"
  [[params.additional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
